<font color = red size = 5>立此为证</font>

             语文	数学	Python  
        
张三	期中	  50   132	 10  


      期末   117	 22	   9  

李四	期中	  76   113	 50  
 
     期末	    8	23	  19  

活齐  期中	   2  86    70  

      期末    148  50  141

In [1]:
import numpy as np

import pandas as pd
from pandas import Series,DataFrame

In [5]:
df = DataFrame(np.random.randint(0,150,size = (6,3)),
               columns=['Python','Math','En'],
               index=pd.MultiIndex.from_product([['张三','李四','A活宝'],['期中','期末']]))
df

        Python  Math   En
张三  期中      38    16   74
    期末     107   100   48
李四  期中      12    44  132
    期末      37    46   69
A活宝 期中      16    45   43
    期末      47   120   70

In [7]:
df2 = DataFrame(np.random.randint(0,150,size = (3,3)),
               columns=['Python','Math','En'],
               index=['张三','李四','A活宝'])
df2

     Python  Math  En
张三      104    70  99
李四        7    46  62
A活宝     140   125  60

In [8]:
df2.loc['张三':'A活宝']

     Python  Math  En
张三      104    70  99
李四        7    46  62
A活宝     140   125  60

In [6]:
df.loc['张三':'A活宝']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [10]:
df3 = df.sort_index()
df3

        Python  Math   En
A活宝 期中      16    45   43
    期末      47   120   70
张三  期中      38    16   74
    期末     107   100   48
李四  期中      12    44  132
    期末      37    46   69

In [11]:
df3.loc['A活宝':'李四']

        Python  Math   En
A活宝 期中      16    45   43
    期末      47   120   70
张三  期中      38    16   74
    期末     107   100   48
李四  期中      12    44  132
    期末      37    46   69

# pandas数据处理

## 1、删除重复元素

使用duplicated()函数检测重复的行，返回元素为布尔类型的Series对象，每个元素对应一行，如果该行不是第一次出现，则元素为True

In [12]:
df = DataFrame({'color':['red','blue','yellow','red'],'price':[10,15,20,10]})
df

    color  price
0     red     10
1    blue     15
2  yellow     20
3     red     10

使用drop_duplicates()函数删除重复的行

In [13]:
df.drop_duplicates()

    color  price
0     red     10
1    blue     15
2  yellow     20

如果使用pd.concat([df1,df2],axis = 1)生成新的DataFrame，新的df中columns相同，使用duplicate()和drop_duplicates()都会出问题

## 2. 映射

映射的含义：创建一个映射关系列表，把values元素和一个特定的标签或者字符串绑定

需要使用字典：

`map = {
    'label1':'value1',
    'label2':'value2',
    ...
    }
`

包含三种操作：

- replace()函数：替换元素
- 最重要：map()函数：新建一列
- rename()函数：替换索引

### 1) replace()函数：替换元素

In [14]:
df

    color  price
0     red     10
1    blue     15
2  yellow     20
3     red     10

In [18]:
df

    color  price
0     red     10
1    blue     15
2  yellow     20
3     red     10

In [22]:
df.replace({10:18,15:22,55:30},limit=-1,inplace = True)

In [23]:
df

    color  price
0     red     18
1    blue     22
2  yellow     20
3     red     18

使用replace()函数，对values进行替换操作

首先定义一个字典

调用.replace()

replace还经常用来替换NaN元素

============================================

练习19：

    假设张三李四的课表里有满分的情况，老师认为是作弊，把所有满分的情况（包括150,300分）都记0分，如何实现？

============================================

### 2) map()函数：新建一列

使用map()函数，由已有的列生成一个新列

适合处理某一单独的列。

In [24]:
df = DataFrame(np.random.randint(0,150,size = (100,3)),columns=['Python','Math','En'])
df

    Python  Math   En
0       60    71   64
1       81    32   12
2       42   100   17
3       45    95   92
4       44    11   44
5      124   125   57
6        6   107   65
7       64   136  132
8       74     3  100
9       58    43   54
10     132   118   98
11      21   107   25
12      61    96  145
13     148    22   26
14      33   128    6
15      52    63   45
16      60   116   94
17       3    25   43
18      57   111  135
19      27     8  115
20     102   146   59
21      55    37   54
22     121   146   49
23     141    71   55
24      48    10   69
25     131    19   33
26      25    30   98
27      27    45   78
28      93   117  133
29     142   107    8
..     ...   ...  ...
70     111    46  146
71      66    48  139
72     147   121   94
73       4   128   93
74      17   103   14
75      84    25   35
76     120    48  127
77     110    91   38
78      61     7  147
79      66   122   64
80      69    16  126
81      81    79   96
82      39    33   52
83     137    86  113
84     125   143  104
85       9     1  118
86      66    39   27
87     113   126  115
88     118    50  124
89      87    50   52
90     119   148   81
91      15    51  125
92      99    81  132
93     103   119   79
94       7    19  106
95      28    23   77
96      83    68   75
97     120     5   44
98     121    79  146
99     112   120  141

[100 rows x 3 columns]

In [25]:
df['Python'] = df['Python'].map(lambda x : x + 10)
df

    Python  Math   En
0       70    71   64
1       91    32   12
2       52   100   17
3       55    95   92
4       54    11   44
5      134   125   57
6       16   107   65
7       74   136  132
8       84     3  100
9       68    43   54
10     142   118   98
11      31   107   25
12      71    96  145
13     158    22   26
14      43   128    6
15      62    63   45
16      70   116   94
17      13    25   43
18      67   111  135
19      37     8  115
20     112   146   59
21      65    37   54
22     131   146   49
23     151    71   55
24      58    10   69
25     141    19   33
26      35    30   98
27      37    45   78
28     103   117  133
29     152   107    8
..     ...   ...  ...
70     121    46  146
71      76    48  139
72     157   121   94
73      14   128   93
74      27   103   14
75      94    25   35
76     130    48  127
77     120    91   38
78      71     7  147
79      76   122   64
80      79    16  126
81      91    79   96
82      49    33   52
83     147    86  113
84     135   143  104
85      19     1  118
86      76    39   27
87     123   126  115
88     128    50  124
89      97    50   52
90     129   148   81
91      25    51  125
92     109    81  132
93     113   119   79
94      17    19  106
95      38    23   77
96      93    68   75
97     130     5   44
98     131    79  146
99     122   120  141

[100 rows x 3 columns]

In [28]:
def convert_level(x):
    if x <60:
        return '不及格'
    elif x < 90:
        return '及格'
    else:
        return '优秀'

df['level'] = df.mean(axis = 1).map(convert_level)

In [30]:
df['Java'] = df['Python'].map(lambda x:x +10)
df

    Python  Math   En level  Java
0       70    71   64    及格    80
1       91    32   12   不及格   101
2       52   100   17   不及格    62
3       55    95   92    及格    65
4       54    11   44   不及格    64
5      134   125   57    优秀   144
6       16   107   65    及格    26
7       74   136  132    优秀    84
8       84     3  100    及格    94
9       68    43   54   不及格    78
10     142   118   98    优秀   152
11      31   107   25   不及格    41
12      71    96  145    优秀    81
13     158    22   26    及格   168
14      43   128    6   不及格    53
15      62    63   45   不及格    72
16      70   116   94    优秀    80
17      13    25   43   不及格    23
18      67   111  135    优秀    77
19      37     8  115   不及格    47
20     112   146   59    优秀   122
21      65    37   54   不及格    75
22     131   146   49    优秀   141
23     151    71   55    优秀   161
24      58    10   69   不及格    68
25     141    19   33    及格   151
26      35    30   98   不及格    45
27      37    45   78   不及格    47
28     103   117  133    优秀   113
29     152   107    8    及格   162
..     ...   ...  ...   ...   ...
70     121    46  146    优秀   131
71      76    48  139    及格    86
72     157   121   94    优秀   167
73      14   128   93    及格    24
74      27   103   14   不及格    37
75      94    25   35   不及格   104
76     130    48  127    优秀   140
77     120    91   38    及格   130
78      71     7  147    及格    81
79      76   122   64    及格    86
80      79    16  126    及格    89
81      91    79   96    及格   101
82      49    33   52   不及格    59
83     147    86  113    优秀   157
84     135   143  104    优秀   145
85      19     1  118   不及格    29
86      76    39   27   不及格    86
87     123   126  115    优秀   133
88     128    50  124    优秀   138
89      97    50   52    及格   107
90     129   148   81    优秀   139
91      25    51  125    及格    35
92     109    81  132    优秀   119
93     113   119   79    优秀   123
94      17    19  106   不及格    27
95      38    23   77   不及格    48
96      93    68   75    及格   103
97     130     5   44   不及格   140
98     131    79  146    优秀   141
99     122   120  141    优秀   132

[100 rows x 5 columns]

In [31]:
df.corr()

          Python      Math        En      Java
Python  1.000000  0.260772 -0.076248  1.000000
Math    0.260772  1.000000  0.113391  0.260772
En     -0.076248  0.113391  1.000000 -0.076248
Java    1.000000  0.260772 -0.076248  1.000000

In [32]:
df['Chinese'] = df['Python'].map(lambda x : x**0.5)

In [33]:
df

    Python  Math   En level  Java    Chinese
0       70    71   64    及格    80   8.366600
1       91    32   12   不及格   101   9.539392
2       52   100   17   不及格    62   7.211103
3       55    95   92    及格    65   7.416198
4       54    11   44   不及格    64   7.348469
5      134   125   57    优秀   144  11.575837
6       16   107   65    及格    26   4.000000
7       74   136  132    优秀    84   8.602325
8       84     3  100    及格    94   9.165151
9       68    43   54   不及格    78   8.246211
10     142   118   98    优秀   152  11.916375
11      31   107   25   不及格    41   5.567764
12      71    96  145    优秀    81   8.426150
13     158    22   26    及格   168  12.569805
14      43   128    6   不及格    53   6.557439
15      62    63   45   不及格    72   7.874008
16      70   116   94    优秀    80   8.366600
17      13    25   43   不及格    23   3.605551
18      67   111  135    优秀    77   8.185353
19      37     8  115   不及格    47   6.082763
20     112   146   59    优秀   122  10.583005
21      65    37   54   不及格    75   8.062258
22     131   146   49    优秀   141  11.445523
23     151    71   55    优秀   161  12.288206
24      58    10   69   不及格    68   7.615773
25     141    19   33    及格   151  11.874342
26      35    30   98   不及格    45   5.916080
27      37    45   78   不及格    47   6.082763
28     103   117  133    优秀   113  10.148892
29     152   107    8    及格   162  12.328828
..     ...   ...  ...   ...   ...        ...
70     121    46  146    优秀   131  11.000000
71      76    48  139    及格    86   8.717798
72     157   121   94    优秀   167  12.529964
73      14   128   93    及格    24   3.741657
74      27   103   14   不及格    37   5.196152
75      94    25   35   不及格   104   9.695360
76     130    48  127    优秀   140  11.401754
77     120    91   38    及格   130  10.954451
78      71     7  147    及格    81   8.426150
79      76   122   64    及格    86   8.717798
80      79    16  126    及格    89   8.888194
81      91    79   96    及格   101   9.539392
82      49    33   52   不及格    59   7.000000
83     147    86  113    优秀   157  12.124356
84     135   143  104    优秀   145  11.618950
85      19     1  118   不及格    29   4.358899
86      76    39   27   不及格    86   8.717798
87     123   126  115    优秀   133  11.090537
88     128    50  124    优秀   138  11.313708
89      97    50   52    及格   107   9.848858
90     129   148   81    优秀   139  11.357817
91      25    51  125    及格    35   5.000000
92     109    81  132    优秀   119  10.440307
93     113   119   79    优秀   123  10.630146
94      17    19  106   不及格    27   4.123106
95      38    23   77   不及格    48   6.164414
96      93    68   75    及格   103   9.643651
97     130     5   44   不及格   140  11.401754
98     131    79  146    优秀   141  11.445523
99     122   120  141    优秀   132  11.045361

[100 rows x 6 columns]

In [34]:
df.corr()

           Python      Math        En      Java   Chinese
Python   1.000000  0.260772 -0.076248  1.000000  0.989193
Math     0.260772  1.000000  0.113391  0.260772  0.262168
En      -0.076248  0.113391  1.000000 -0.076248 -0.069933
Java     1.000000  0.260772 -0.076248  1.000000  0.989193
Chinese  0.989193  0.262168 -0.069933  0.989193  1.000000

仍然是新建一个字典

map()函数中可以使用lambda函数

transform()和map()类似

In [36]:
df.head()

   Python  Math  En level  Java   Chinese
0      70    71  64    及格    80  8.366600
1      91    32  12   不及格   101  9.539392
2      52   100  17   不及格    62  7.211103
3      55    95  92    及格    65  7.416198
4      54    11  44   不及格    64  7.348469

In [37]:
df['Chem'] = df['Python'].map(lambda x :x/2) + df['Java'].map(lambda x : x/2)

In [38]:
df

    Python  Math   En level  Java    Chinese   Chem
0       70    71   64    及格    80   8.366600   75.0
1       91    32   12   不及格   101   9.539392   96.0
2       52   100   17   不及格    62   7.211103   57.0
3       55    95   92    及格    65   7.416198   60.0
4       54    11   44   不及格    64   7.348469   59.0
5      134   125   57    优秀   144  11.575837  139.0
6       16   107   65    及格    26   4.000000   21.0
7       74   136  132    优秀    84   8.602325   79.0
8       84     3  100    及格    94   9.165151   89.0
9       68    43   54   不及格    78   8.246211   73.0
10     142   118   98    优秀   152  11.916375  147.0
11      31   107   25   不及格    41   5.567764   36.0
12      71    96  145    优秀    81   8.426150   76.0
13     158    22   26    及格   168  12.569805  163.0
14      43   128    6   不及格    53   6.557439   48.0
15      62    63   45   不及格    72   7.874008   67.0
16      70   116   94    优秀    80   8.366600   75.0
17      13    25   43   不及格    23   3.605551   18.0
18      67   111  135    优秀    77   8.185353   72.0
19      37     8  115   不及格    47   6.082763   42.0
20     112   146   59    优秀   122  10.583005  117.0
21      65    37   54   不及格    75   8.062258   70.0
22     131   146   49    优秀   141  11.445523  136.0
23     151    71   55    优秀   161  12.288206  156.0
24      58    10   69   不及格    68   7.615773   63.0
25     141    19   33    及格   151  11.874342  146.0
26      35    30   98   不及格    45   5.916080   40.0
27      37    45   78   不及格    47   6.082763   42.0
28     103   117  133    优秀   113  10.148892  108.0
29     152   107    8    及格   162  12.328828  157.0
..     ...   ...  ...   ...   ...        ...    ...
70     121    46  146    优秀   131  11.000000  126.0
71      76    48  139    及格    86   8.717798   81.0
72     157   121   94    优秀   167  12.529964  162.0
73      14   128   93    及格    24   3.741657   19.0
74      27   103   14   不及格    37   5.196152   32.0
75      94    25   35   不及格   104   9.695360   99.0
76     130    48  127    优秀   140  11.401754  135.0
77     120    91   38    及格   130  10.954451  125.0
78      71     7  147    及格    81   8.426150   76.0
79      76   122   64    及格    86   8.717798   81.0
80      79    16  126    及格    89   8.888194   84.0
81      91    79   96    及格   101   9.539392   96.0
82      49    33   52   不及格    59   7.000000   54.0
83     147    86  113    优秀   157  12.124356  152.0
84     135   143  104    优秀   145  11.618950  140.0
85      19     1  118   不及格    29   4.358899   24.0
86      76    39   27   不及格    86   8.717798   81.0
87     123   126  115    优秀   133  11.090537  128.0
88     128    50  124    优秀   138  11.313708  133.0
89      97    50   52    及格   107   9.848858  102.0
90     129   148   81    优秀   139  11.357817  134.0
91      25    51  125    及格    35   5.000000   30.0
92     109    81  132    优秀   119  10.440307  114.0
93     113   119   79    优秀   123  10.630146  118.0
94      17    19  106   不及格    27   4.123106   22.0
95      38    23   77   不及格    48   6.164414   43.0
96      93    68   75    及格   103   9.643651   98.0
97     130     5   44   不及格   140  11.401754  135.0
98     131    79  146    优秀   141  11.445523  136.0
99     122   120  141    优秀   132  11.045361  127.0

[100 rows x 7 columns]

In [39]:
s = df['Python']

In [40]:
s.transform(lambda x : x*2)

0     140
1     182
2     104
3     110
4     108
5     268
6      32
7     148
8     168
9     136
10    284
11     62
12    142
13    316
14     86
15    124
16    140
17     26
18    134
19     74
20    224
21    130
22    262
23    302
24    116
25    282
26     70
27     74
28    206
29    304
     ...
70    242
71    152
72    314
73     28
74     54
75    188
76    260
77    240
78    142
79    152
80    158
81    182
82     98
83    294
84    270
85     38
86    152
87    246
88    256
89    194
90    258
91     50
92    218
93    226
94     34
95     76
96    186
97    260
98    262
99    244
Name: Python, Length: 100, dtype: int64

In [41]:
df.shape

(100, 7)

In [42]:
df['price'] = np.random.randint(150,699,size = 100)

In [44]:
df['count'] = np.random.randint(2,10,size = 100)

In [45]:
df.head()

   Python  Math  En level  Java   Chinese  Chem  price  count
0      70    71  64    及格    80  8.366600  75.0    487      5
1      91    32  12   不及格   101  9.539392  96.0    236      2
2      52   100  17   不及格    62  7.211103  57.0    156      4
3      55    95  92    及格    65  7.416198  60.0    348      5
4      54    11  44   不及格    64  7.348469  59.0    381      7

In [47]:
df.count

<bound method DataFrame.count of     Python  Math   En level  Java    Chinese   Chem  price  count
0       70    71   64    及格    80   8.366600   75.0    487      5
1       91    32   12   不及格   101   9.539392   96.0    236      2
2       52   100   17   不及格    62   7.211103   57.0    156      4
3       55    95   92    及格    65   7.416198   60.0    348      5
4       54    11   44   不及格    64   7.348469   59.0    381      7
5      134   125   57    优秀   144  11.575837  139.0    604      8
6       16   107   65    及格    26   4.000000   21.0    655      4
7       74   136  132    优秀    84   8.602325   79.0    316      8
8       84     3  100    及格    94   9.165151   89.0    474      7
9       68    43   54   不及格    78   8.246211   73.0    597      7
10     142   118   98    优秀   152  11.916375  147.0    393      8
11      31   107   25   不及格    41   5.567764   36.0    332      8
12      71    96  145    优秀    81   8.426150   76.0    680      3
13     158    22   26    及格   168  12.569805  163.0    203      7
14      43   128    6   不及格    53   6.557439   48.0    241      6
15      62    63   45   不及格    72   7.874008   67.0    505      9
16      70   116   94    优秀    80   8.366600   75.0    461      9
17      13    25   43   不及格    23   3.605551   18.0    379      7
18      67   111  135    优秀    77   8.185353   72.0    423      3
19      37     8  115   不及格    47   6.082763   42.0    535      4
20     112   146   59    优秀   122  10.583005  117.0    490      4
21      65    37   54   不及格    75   8.062258   70.0    460      8
22     131   146   49    优秀   141  11.445523  136.0    572      3
23     151    71   55    优秀   161  12.288206  156.0    647      3
24      58    10   69   不及格    68   7.615773   63.0    503      5
25     141    19   33    及格   151  11.874342  146.0    664      3
26      35    30   98   不及格    45   5.916080   40.0    545      4
27      37    45   78   不及格    47   6.082763   42.0    535      5
28     103   117  133    优秀   113  10.148892  108.0    548      9
29     152   107    8    及格   162  12.328828  157.0    491      6
..     ...   ...  ...   ...   ...        ...    ...    ...    ...
70     121    46  146    优秀   131  11.000000  126.0    515      3
71      76    48  139    及格    86   8.717798   81.0    655      7
72     157   121   94    优秀   167  12.529964  162.0    588      2
73      14   128   93    及格    24   3.741657   19.0    663      3
74      27   103   14   不及格    37   5.196152   32.0    333      8
75      94    25   35   不及格   104   9.695360   99.0    190      8
76     130    48  127    优秀   140  11.401754  135.0    248      3
77     120    91   38    及格   130  10.954451  125.0    532      7
78      71     7  147    及格    81   8.426150   76.0    316      4
79      76   122   64    及格    86   8.717798   81.0    301      3
80      79    16  126    及格    89   8.888194   84.0    661      2
81      91    79   96    及格   101   9.539392   96.0    479      5
82      49    33   52   不及格    59   7.000000   54.0    489      8
83     147    86  113    优秀   157  12.124356  152.0    536      4
84     135   143  104    优秀   145  11.618950  140.0    255      2
85      19     1  118   不及格    29   4.358899   24.0    314      4
86      76    39   27   不及格    86   8.717798   81.0    282      4
87     123   126  115    优秀   133  11.090537  128.0    291      3
88     128    50  124    优秀   138  11.313708  133.0    245      6
89      97    50   52    及格   107   9.848858  102.0    446      8
90     129   148   81    优秀   139  11.357817  134.0    164      6
91      25    51  125    及格    35   5.000000   30.0    276      8
92     109    81  132    优秀   119  10.440307  114.0    598      4
93     113   119   79    优秀   123  10.630146  118.0    160      3
94      17    19  106   不及格    27   4.123106   22.0    636      4
95      38    23   77   不及格    48   6.164414   43.0    450      2
96      93    68   75    及格   103   9.643651   98.0    445      5
97     130     5   44   不及格   140  11.401754  135.0    473      3
98     131    79  146    优秀   141  11.445523  136.0    614      9
99     122   120  141    优秀   132  11.045361  127.0    433      6

[100 rows x 9 columns]>

In [48]:
df['total'] = df.price*df['count']

In [49]:
df.head()

   Python  Math  En level  Java   Chinese  Chem  price  count  total
0      70    71  64    及格    80  8.366600  75.0    487      5   2435
1      91    32  12   不及格   101  9.539392  96.0    236      2    472
2      52   100  17   不及格    62  7.211103  57.0    156      4    624
3      55    95  92    及格    65  7.416198  60.0    348      5   1740
4      54    11  44   不及格    64  7.348469  59.0    381      7   2667

使用map()函数新建一个新列

============================================

练习20：

    新增两列，分别为张三、李四的成绩状态，如果分数低于90，则为"failed"，如果分数高于120，则为"excellent"，其他则为"pass"
    
    【提示】使用函数作为map的参数

============================================

### 3) rename()函数：替换索引

In [52]:
df.rename({0:'A',2:'B'},inplace=True)

In [54]:
df.rename({'En':'英语','Chinese':'国语'},axis = 1,inplace=True)
df

    Python  Math   英语 level  Java         国语   Chem  price  count  total
A       70    71   64    及格    80   8.366600   75.0    487      5   2435
1       91    32   12   不及格   101   9.539392   96.0    236      2    472
B       52   100   17   不及格    62   7.211103   57.0    156      4    624
3       55    95   92    及格    65   7.416198   60.0    348      5   1740
4       54    11   44   不及格    64   7.348469   59.0    381      7   2667
5      134   125   57    优秀   144  11.575837  139.0    604      8   4832
6       16   107   65    及格    26   4.000000   21.0    655      4   2620
7       74   136  132    优秀    84   8.602325   79.0    316      8   2528
8       84     3  100    及格    94   9.165151   89.0    474      7   3318
9       68    43   54   不及格    78   8.246211   73.0    597      7   4179
10     142   118   98    优秀   152  11.916375  147.0    393      8   3144
11      31   107   25   不及格    41   5.567764   36.0    332      8   2656
12      71    96  145    优秀    81   8.426150   76.0    680      3   2040
13     158    22   26    及格   168  12.569805  163.0    203      7   1421
14      43   128    6   不及格    53   6.557439   48.0    241      6   1446
15      62    63   45   不及格    72   7.874008   67.0    505      9   4545
16      70   116   94    优秀    80   8.366600   75.0    461      9   4149
17      13    25   43   不及格    23   3.605551   18.0    379      7   2653
18      67   111  135    优秀    77   8.185353   72.0    423      3   1269
19      37     8  115   不及格    47   6.082763   42.0    535      4   2140
20     112   146   59    优秀   122  10.583005  117.0    490      4   1960
21      65    37   54   不及格    75   8.062258   70.0    460      8   3680
22     131   146   49    优秀   141  11.445523  136.0    572      3   1716
23     151    71   55    优秀   161  12.288206  156.0    647      3   1941
24      58    10   69   不及格    68   7.615773   63.0    503      5   2515
25     141    19   33    及格   151  11.874342  146.0    664      3   1992
26      35    30   98   不及格    45   5.916080   40.0    545      4   2180
27      37    45   78   不及格    47   6.082763   42.0    535      5   2675
28     103   117  133    优秀   113  10.148892  108.0    548      9   4932
29     152   107    8    及格   162  12.328828  157.0    491      6   2946
..     ...   ...  ...   ...   ...        ...    ...    ...    ...    ...
70     121    46  146    优秀   131  11.000000  126.0    515      3   1545
71      76    48  139    及格    86   8.717798   81.0    655      7   4585
72     157   121   94    优秀   167  12.529964  162.0    588      2   1176
73      14   128   93    及格    24   3.741657   19.0    663      3   1989
74      27   103   14   不及格    37   5.196152   32.0    333      8   2664
75      94    25   35   不及格   104   9.695360   99.0    190      8   1520
76     130    48  127    优秀   140  11.401754  135.0    248      3    744
77     120    91   38    及格   130  10.954451  125.0    532      7   3724
78      71     7  147    及格    81   8.426150   76.0    316      4   1264
79      76   122   64    及格    86   8.717798   81.0    301      3    903
80      79    16  126    及格    89   8.888194   84.0    661      2   1322
81      91    79   96    及格   101   9.539392   96.0    479      5   2395
82      49    33   52   不及格    59   7.000000   54.0    489      8   3912
83     147    86  113    优秀   157  12.124356  152.0    536      4   2144
84     135   143  104    优秀   145  11.618950  140.0    255      2    510
85      19     1  118   不及格    29   4.358899   24.0    314      4   1256
86      76    39   27   不及格    86   8.717798   81.0    282      4   1128
87     123   126  115    优秀   133  11.090537  128.0    291      3    873
88     128    50  124    优秀   138  11.313708  133.0    245      6   1470
89      97    50   52    及格   107   9.848858  102.0    446      8   3568
90     129   148   81    优秀   139  11.357817  134.0    164      6    984
91      25    51  125    及格    35   5.000000   30.0    276      8   2208
92     109    81  132    优秀   119  10.440307  114.0    598      4   2392
93     113   119   79    优秀   123  10.630146  118.0    160      3    480
94      17    19  106   不及格    27   4.123106   22.0    636      4   2544
95      38    23   77   不及格    48   6.164414   43.0    450      2    900
96      93    68   75    及格   103   9.643651   98.0    445      5   2225
97     130     5   44   不及格   140  11.401754  135.0    473      3   1419
98     131    79  146    优秀   141  11.445523  136.0    614      9   5526
99     122   120  141    优秀   132  11.045361  127.0    433      6   2598

[100 rows x 10 columns]

仍然是新建一个字典

使用rename()函数替换行索引

## 3. 异常值检测和过滤

使用describe()函数查看每一列的描述性统计量

In [55]:
# 正太分布
df = DataFrame(np.random.randn(100000,3),columns = ['red','green','blue'])
df

            red     green      blue
0      0.457195  0.066083 -0.245221
1      1.669700  0.851379  0.374052
2     -1.064747  0.337835  0.035491
3     -0.704666  0.496532  1.330204
4     -1.765488 -0.836792 -0.042202
5      0.529513  0.733836 -0.216044
6      0.073336 -0.082088 -0.179906
7      1.277652  0.894939 -0.176003
8      0.043221 -1.065549  1.419470
9      1.583946  0.394116  0.133525
10    -0.207429 -1.251262 -0.242227
11     1.169561  0.180522 -0.299846
12    -0.568674 -0.765684 -0.688425
13    -0.610585 -0.538233 -0.629391
14     1.962415  0.509814 -1.124970
15     0.596218  0.184946  0.256183
16    -0.563681  0.578782  1.001190
17     1.027622  0.500253  0.658718
18    -0.670608  0.949093 -1.783274
19     1.448138  0.933498 -0.556734
20    -1.424046  0.022944  0.017823
21    -2.635357  0.223422 -1.686867
22    -1.051269  0.075578  0.505669
23     1.059019 -1.457218 -1.170751
24    -1.195815 -0.375983 -0.647409
25    -0.940073  0.411450 -0.646082
26     0.888133 -0.339481  1.344312
27    -1.032185 -0.352349  0.119251
28     0.963969 -1.497916 -0.689502
29    -0.025220 -0.098721 -0.697010
...         ...       ...       ...
99970 -1.589575  0.574468 -0.277965
99971 -0.196792 -0.151440 -2.493546
99972 -1.050620 -0.253625 -0.391640
99973  1.130737  0.068169  0.420117
99974  0.055332  0.897858  0.078118
99975 -1.872495 -0.884242  1.677444
99976 -1.314469 -1.889679  0.070214
99977 -0.954727 -2.020302 -0.290879
99978  1.555498 -0.094177  1.154342
99979 -2.057607  0.388896  0.478105
99980  0.066268  1.243497  0.100062
99981  1.406554 -0.212633  0.152998
99982 -0.080106 -0.168582  0.123863
99983  2.159762  0.183815 -0.891361
99984 -0.738767 -0.470182  0.240647
99985  0.255384  1.703727 -0.973747
99986  1.517820 -2.047810 -0.484716
99987  0.377634 -2.221260 -0.070579
99988 -1.628837  0.485343  2.015527
99989  1.338598 -1.828759 -0.156960
99990  0.111943  1.050493 -1.829312
99991  1.133819  1.991150  0.650699
99992 -1.133285  0.300701 -1.854954
99993 -0.601844  0.434420 -0.856489
99994  0.140849 -0.424854 -1.099558
99995  1.728145  2.395733  0.068300
99996 -0.710882 -1.090885  1.009380
99997 -0.257462 -0.657151  1.636800
99998  0.082724  1.514570 -0.690906
99999  2.064030 -1.477599  0.646720

[100000 rows x 3 columns]

In [56]:
df.abs()

            red     green      blue
0      0.457195  0.066083  0.245221
1      1.669700  0.851379  0.374052
2      1.064747  0.337835  0.035491
3      0.704666  0.496532  1.330204
4      1.765488  0.836792  0.042202
5      0.529513  0.733836  0.216044
6      0.073336  0.082088  0.179906
7      1.277652  0.894939  0.176003
8      0.043221  1.065549  1.419470
9      1.583946  0.394116  0.133525
10     0.207429  1.251262  0.242227
11     1.169561  0.180522  0.299846
12     0.568674  0.765684  0.688425
13     0.610585  0.538233  0.629391
14     1.962415  0.509814  1.124970
15     0.596218  0.184946  0.256183
16     0.563681  0.578782  1.001190
17     1.027622  0.500253  0.658718
18     0.670608  0.949093  1.783274
19     1.448138  0.933498  0.556734
20     1.424046  0.022944  0.017823
21     2.635357  0.223422  1.686867
22     1.051269  0.075578  0.505669
23     1.059019  1.457218  1.170751
24     1.195815  0.375983  0.647409
25     0.940073  0.411450  0.646082
26     0.888133  0.339481  1.344312
27     1.032185  0.352349  0.119251
28     0.963969  1.497916  0.689502
29     0.025220  0.098721  0.697010
...         ...       ...       ...
99970  1.589575  0.574468  0.277965
99971  0.196792  0.151440  2.493546
99972  1.050620  0.253625  0.391640
99973  1.130737  0.068169  0.420117
99974  0.055332  0.897858  0.078118
99975  1.872495  0.884242  1.677444
99976  1.314469  1.889679  0.070214
99977  0.954727  2.020302  0.290879
99978  1.555498  0.094177  1.154342
99979  2.057607  0.388896  0.478105
99980  0.066268  1.243497  0.100062
99981  1.406554  0.212633  0.152998
99982  0.080106  0.168582  0.123863
99983  2.159762  0.183815  0.891361
99984  0.738767  0.470182  0.240647
99985  0.255384  1.703727  0.973747
99986  1.517820  2.047810  0.484716
99987  0.377634  2.221260  0.070579
99988  1.628837  0.485343  2.015527
99989  1.338598  1.828759  0.156960
99990  0.111943  1.050493  1.829312
99991  1.133819  1.991150  0.650699
99992  1.133285  0.300701  1.854954
99993  0.601844  0.434420  0.856489
99994  0.140849  0.424854  1.099558
99995  1.728145  2.395733  0.068300
99996  0.710882  1.090885  1.009380
99997  0.257462  0.657151  1.636800
99998  0.082724  1.514570  0.690906
99999  2.064030  1.477599  0.646720

[100000 rows x 3 columns]

In [58]:
cond = df.abs() - df.mean() > 3*df.std()
cond.sum()

red      255
green    249
blue     285
dtype: int64

In [61]:
cond = cond.any(axis = 1)
df[cond]

            red     green      blue
82     0.333661 -3.167631 -1.883697
184    1.041021 -3.159097  1.855978
301    1.592066  0.562511  3.040302
321    3.169799 -0.657458 -0.968745
385   -1.318554  0.343788 -3.248062
468    3.852547 -0.990149 -0.295601
736   -0.644689 -3.484493 -0.903205
834    3.668372 -0.401343 -0.174164
1010   3.109958 -0.443491 -0.772549
1088   1.143069  3.101547 -0.136341
1097  -0.438637  3.195605  1.259711
1105   0.324043  0.376975  3.522120
1130   0.418215  3.350011 -0.411537
1283  -3.273169  0.298164 -0.593433
1456  -3.008107  0.733937  0.733499
2003   0.908975  3.340519 -1.015471
2086   1.195447  1.503325 -3.649463
2296  -0.897166  3.337259  0.208554
2450  -3.101208 -0.532990 -1.341568
2497   3.142854 -0.168011 -1.230107
2502   3.400119  0.264605  1.611500
2546   3.457080  0.480629 -1.264021
2568  -3.513747 -0.429523  2.035549
2610   0.363927 -3.005188 -0.426479
2728   1.463050  0.377904 -3.011537
2943   0.236785  0.389124 -3.050922
3321   0.483895  1.204039  3.273332
3448   0.389333  0.084776 -3.200958
3592  -3.065914 -0.231544 -1.996560
3710   0.616297  1.799416 -3.163016
...         ...       ...       ...
96589 -1.258259  3.495011  0.109192
96762  3.330045 -0.990436 -0.895287
97225  3.167552 -2.141755  0.411406
97227 -3.249078  1.370191  1.605363
97270 -3.199357 -0.540904  0.240828
97464  1.155114  3.041734  3.065999
97478 -3.009036  1.920678 -0.124145
97803 -0.253567  0.875569 -3.287762
97841 -3.003925  0.199870  0.610357
98145  3.037830  1.819041  0.930837
98158  0.688636 -0.166366  3.335482
98167 -0.682641  2.330832 -3.336790
98528  0.574028 -0.337258 -3.679103
98542 -0.636181 -0.781722 -3.096024
98590 -3.173216 -0.259874 -0.098411
98598  1.180888 -0.691110  4.082645
98602 -3.151046 -0.591259 -0.281794
98676 -3.050089 -1.234629  1.686170
98789  0.316120 -0.411696  3.424071
98895  3.122684 -0.940161 -2.384330
98897 -3.041669 -1.377633  1.160734
99115 -0.254681  0.868280  3.224737
99175 -3.266862 -0.089625  0.101131
99178 -0.867487  1.470227  3.661405
99215 -3.061528  0.315719  0.564106
99435 -0.179364 -0.397503 -3.123434
99532  0.719460 -0.568000  3.006943
99557  0.006459  3.067967 -0.672683
99619  0.491586  0.002077  3.114900
99952  3.068155 -0.757346 -0.269756

[785 rows x 3 columns]

In [63]:
df2 = df.drop(labels=df[cond].index)

In [64]:
df.shape

(100000, 3)

In [65]:
df2.shape

(99215, 3)

In [66]:
# 异常值过滤
700/100000

0.007

使用std()函数可以求得DataFrame对象每一列的标准差

根据每一列的标准差，对DataFrame元素进行过滤。

借助any()函数, 测试是否有True，有一个或以上返回True，反之返回False

对每一列应用筛选条件,去除标准差太大的数据

删除特定索引df.drop(labels,inplace = True)

============================================

练习21：

    新建一个形状为10000*3的标准正态分布的DataFrame(np.random.randn)，去除掉所有满足以下情况的行：其中任一元素绝对值大于3倍标准差

============================================

## 4. 排序

使用.take()函数排序

可以借助np.random.permutation()函数随机排序

In [69]:
df.sort_values(by = 'red',ascending=False)

            red     green      blue
53567  4.390790 -0.529384 -1.289757
84959  4.215555 -0.662610  1.458260
46881  4.001839  0.247104 -0.009685
93269  3.956247 -1.122577  0.499276
59553  3.881502  0.448247  0.698172
30546  3.852878 -1.686899  2.093841
468    3.852547 -0.990149 -0.295601
46342  3.843351 -1.146183 -0.910100
55779  3.814610 -1.155167 -0.163461
83540  3.787959  1.378842  0.442158
66773  3.741506 -0.406375 -0.144387
44976  3.736948 -1.243936 -0.869852
15100  3.719475 -0.173725  2.155328
834    3.668372 -0.401343 -0.174164
51345  3.640117 -0.631336 -0.891509
5223   3.639362 -0.990722  0.356106
36567  3.609003  0.238968  0.074142
48278  3.582672 -0.477566  0.971101
61464  3.563778 -1.166435 -0.938257
23367  3.559778  1.517321 -0.744574
46043  3.546048 -1.033275  0.990131
24169  3.528085 -0.156216  1.653352
30367  3.497664 -1.181998 -0.695553
61729  3.485500 -3.373053  0.318538
31344  3.478936  1.664323  1.136469
11910  3.477871 -0.687817  0.992421
26143  3.457709 -0.133250 -0.961300
2546   3.457080  0.480629 -1.264021
40479  3.435087 -1.655355  0.771961
86373  3.429359 -0.191404 -0.261407
...         ...       ...       ...
11392 -3.398449 -2.683306  0.125485
5852  -3.405085 -1.437730  0.515100
79789 -3.408336 -0.339516 -0.412650
27693 -3.431068  1.388889  1.619761
51549 -3.433862  0.896996 -1.616757
84501 -3.439135 -0.327031  0.028851
58188 -3.450691  0.409997 -1.627256
6722  -3.469697  1.990269  0.598641
82346 -3.511901 -1.937648  0.557105
2568  -3.513747 -0.429523  2.035549
52054 -3.524703  0.537916 -0.544679
90878 -3.525791  0.655598 -0.947596
19599 -3.532030 -0.623252  0.433994
46272 -3.537225  0.623083  1.170939
31348 -3.537679  0.884298 -0.368356
91675 -3.550982 -0.658497 -1.049746
24178 -3.585063  0.494379 -0.269928
39982 -3.586921 -0.433652  0.525129
35977 -3.612367 -0.347257  0.449128
81322 -3.619806  1.152838 -0.599778
23356 -3.625845  1.429202 -0.335353
95697 -3.659082  2.328867 -2.274716
82184 -3.677289  2.481936 -0.109415
93395 -3.766380  0.535743 -1.033164
48158 -3.810029  0.954572 -0.083237
54535 -3.860189 -0.304780 -1.125868
55108 -3.904556 -0.844047  0.085645
12005 -3.966111  0.841661  0.305736
34256 -4.016705 -1.201664  1.068135
77560 -4.236985 -0.327540 -1.873766

[100000 rows x 3 columns]

In [70]:
df.shape

(100000, 3)

In [71]:
index = np.random.randint(0,100000,size = 1000)
index

array([66802, 96945, 28507, 13556,  5806, 19820, 62583, 96696, 70336,
       60913,  3024,  7119, 23414,  7976, 60371, 88647, 51866, 14849,
       81793, 53701, 60607, 78552, 34810, 70528, 31556, 96027, 75783,
        9820, 89022, 25889, 84182, 81804, 97820, 62606, 16272, 25817,
       21242, 61340, 14076, 20491, 52536,  2651, 48675, 47714, 61650,
       52523, 40382, 82613, 13123, 95719, 37252, 54415, 60169, 24811,
       15855,  6257, 31503, 58169, 55321,  6472, 86219, 82688, 28816,
       30876, 42786, 92514,  6424, 56958, 85926, 58909, 65273, 38818,
       51743, 53613, 83058, 81482, 94367, 31908, 24636, 59683, 80515,
       27747, 55020, 67145, 18407, 91576, 32258, 96966,  2126,  1664,
       12666, 86783, 61863, 25610, 15814, 94604, 75879, 88112, 90683,
       75027, 37299, 61277, 36227, 59438, 34923, 66095, 19353, 97574,
        3311, 73352, 60429, 83390, 86019, 81560, 77735,  7927, 60904,
       43808, 19015, 56158, 29704, 78558, 40253, 17968, 17227, 62874,
       81909, 64106, 97926, 67339, 95347, 42382, 82673, 13510, 56693,
       44263, 78946, 51387, 20323, 28253,  5899,  1490, 74692, 11802,
       57232, 61851,  4854, 92083, 50204, 37102,  1685, 32071, 13557,
       82556, 34071, 88887, 95871,  9625, 30254, 85946, 29519, 21465,
       17912, 70118, 13519, 62886, 21158, 89839, 53560, 29810, 82275,
       15952, 96927, 97169, 60085, 79374, 69540, 32691, 11953, 89176,
       84727, 59802, 31056, 69321, 51012, 22184, 25223, 55957, 96790,
       19551, 10264, 64689, 53994, 52910,  6026, 32636, 28315, 97911,
       84888, 62861, 77242, 19607, 17905, 70457, 51085, 55505, 87778,
       63423, 46920, 85718, 63978,  6577, 73849, 51748, 92641, 71453,
       57427, 16062, 30264, 11464, 14027, 43691, 21965, 83094, 46523,
       30695, 38613,  2951, 66142, 31196, 34218, 35373,  9142, 85290,
       88408,  1681, 80232,  2289, 83794, 35192, 16952, 19061, 26296,
       30082, 60708, 94101, 90708, 69367, 95281, 40064, 85598, 77421,
       37895, 44629,  3476, 86136, 86665, 90025, 22590, 35195, 97783,
       40162, 39901, 20462, 18349, 20016, 67965,  9237, 28527, 57754,
       34563, 99682, 28554,  1243, 64822, 97203,  5674, 52793, 58627,
       84995, 94013, 11123,  4856, 80473, 37615, 13085, 55019, 29904,
       31936, 53183,  7402, 50187, 97948, 54694, 36301, 63319, 38575,
        2338, 29581, 82447, 32423, 47413, 50742, 59379, 10195, 68441,
       95512, 61886, 74104, 57459, 99685, 16670, 35687, 83951, 11299,
       52631, 57904, 51033, 55560, 23116, 97116, 25823, 94654, 72845,
       80487, 29388, 85221, 60312,  3594, 50185, 57553, 64618, 23546,
       35926,  2365, 65242,  7003, 58830, 84161,  4839, 24243, 34090,
       35183, 48586,  2114, 66993, 88204, 99690, 32823, 92709, 41410,
       57716, 41801, 28328, 14971, 26961, 92371,  1789,  8721,  7451,
       76530, 21050, 65123, 44730, 67816, 34507, 23402, 60984, 45200,
       56094, 17826, 52533,  1534, 31462, 23358, 18164, 90214, 16930,
       51590, 67051, 64739, 46052,  1095, 17384, 24933, 77962, 89696,
       40925,  1756, 42672, 93293, 27733, 76151, 89087, 71545, 35002,
       62951, 20902, 94346, 63253, 86540, 14559, 27559, 80507, 52788,
       26575, 33677,  3761, 87436,  7451, 53122, 80116, 32206, 14590,
       81336, 32843, 67442, 39124, 83365, 87146, 80138, 96834, 45122,
       29786, 94242, 50846, 38321,  9409, 16684, 40494, 98000,  6810,
       22615, 34309,  4891, 83009, 57804, 22276, 27788, 14187, 97828,
       56068, 82852, 23439, 49681, 60412, 88147, 74207, 41857, 23769,
       91078, 53664,  5249, 36676, 90651, 80426, 93893, 55003, 51820,
       43982, 18051, 18614, 56162, 31117, 22860, 47024, 81242, 48230,
       14702, 14185, 85460, 60648, 75788, 61988, 45599, 60970, 22124,
       60871, 55710,  2888,  9892, 60779, 59421, 10543, 35165, 20443,
       20843,  9196, 14888, 24740, 91393, 68949, 61468, 46426, 33396,
       77541, 85839, 18924, 62115, 15345, 78459, 65717, 57350, 22239,
       46994, 37143, 50029, 76750, 10861, 48207, 14338, 50428, 83034,
        7095, 81375, 22697, 10989, 96049, 13948, 95218, 87956, 77443,
       26056, 57082, 46000, 85440, 24283, 93117, 26614, 20126, 55603,
       19066, 20053, 26875, 65403, 38826, 61257, 56943,   501, 80510,
       73690, 25376, 73725, 30908, 72210,  6151, 82642, 29112, 99811,
       71666,  6962, 41380, 97627, 12385,  8807, 11010,  6047, 39430,
       55800, 30733, 37886, 51589, 70477, 79429, 39691, 12519, 10470,
       25663, 10702, 42025, 19294, 15236, 33748, 60851, 60563, 23260,
       11491,  4717, 25725, 83677, 27257, 14571, 83915, 58674, 49849,
       42235, 59361, 48041, 99328, 39653, 86517, 48384, 13926, 51160,
       58086, 23211, 28160, 37602, 19660, 21344, 78050, 30673, 14986,
       23746, 47614, 51287, 50089, 90161, 66339, 43909, 45694, 16435,
       20092, 67625, 53896, 36185, 84269, 32305, 47036, 38783, 64540,
       36715, 51245, 84969, 91143, 81395, 58375, 25544, 92109, 20060,
       98466, 45716, 24947, 17804, 67627, 29517, 16988,  7954, 94506,
       53641, 24128, 56452, 33584, 57759, 49902, 73194, 55237, 59432,
       36454,  5349,  8631, 37757, 30594, 40196, 69931, 58769, 44291,
       86759, 40563, 43609, 66636, 16993,  5685, 33822, 85932, 15252,
       68279,  3260, 78420, 67318, 29632, 11903, 28058, 80148, 42337,
       62295, 74103, 40055, 54202,   280, 31738, 60228, 80894, 30582,
       25861,  6773,  1467, 17992, 31062, 82150, 69231, 59438, 32282,
       27353, 30939, 75641, 34007,  6112, 50792, 25333, 73229, 97749,
        2942, 27741, 68266, 53233, 12958, 96661, 11185, 87257, 13850,
        9930, 24947, 36203, 48207, 23082, 56241, 71572, 33621, 60084,
       89682, 74917, 91372, 14071, 82132, 73170, 65703,  6056, 11743,
       43620, 52608, 16767, 76130, 22574,  5399, 56512,  9966, 97528,
       55914, 92770, 97345, 63263, 96860, 35158, 31841, 27978, 50158,
       30561, 74289, 53090, 26710, 26029, 49161, 83290, 12599, 29367,
       75207,  5317, 63295, 57196, 18622, 98009, 90695, 65451, 21944,
       73257, 49812, 79721, 84468, 53957, 32391, 83932, 26771, 78938,
       21107, 79540, 52255, 14408, 57956, 90498, 82398, 72726, 17659,
        3235, 18456, 52439, 72833, 72317, 53222, 74563, 40108, 69243,
       47143, 47400, 25489, 86510,  9566, 67821, 82696, 94153, 64330,
       18577, 35313, 55405, 66877, 20829, 34674, 25030, 44995, 72102,
       12596, 80312, 43108, 83291, 38160,  5223, 44165, 64901, 42198,
       21710,   136, 13306, 47730, 79863, 38058, 34206, 28418, 23484,
       98105, 70534, 54898, 25978, 81365, 61206, 14038, 50066, 99866,
        5402, 13186, 49016, 34969, 57553, 31329, 71314, 10703, 11370,
       80958, 18310, 51352, 60414, 48170, 20624, 58278, 84831,  3385,
       64294, 17226, 45981, 23667, 59674,  4587, 50347, 98747,  6998,
       12371, 67087, 20601, 11729, 33277, 81477, 10666, 15085, 58219,
       26771, 34122, 71368, 51874, 94548, 61369, 88559, 38673, 21997,
        3185,  8446,  8663, 70529,  8215, 36870, 59551, 72235, 48312,
       39351, 53588, 22301, 62017, 62145, 28456, 31150, 86167, 45780,
       81481, 44319, 36393, 86016, 86843, 95396, 37113, 87290, 12840,
        7780, 86208, 47783, 95561, 84559,  4272, 40460, 26686,  3131,
       59008, 27987, 69349, 92921, 25093, 32245, 40024, 21953, 98082,
       67014, 20318, 64141, 88895, 14920, 81580, 62409, 30046, 39456,
       89789, 43321, 24935, 11670, 26374, 70229, 38719, 74794, 99891,
       67776, 37325, 26289, 90041, 35309, 77408,  2402, 47175, 24542,
       13388, 84764, 85105, 23137, 41583, 44330,  8467, 61702, 74938,
       62144, 11996,  8057, 86300, 79483, 74463, 10731, 99394, 92035,
       58295, 98790, 66090, 90449, 14795, 50261, 86578, 32186, 62396,
        8252, 27835, 52407, 31259, 26396, 26680, 62214, 53583,   406,
       99179, 36382, 96144, 56267, 27090, 52813, 97492, 92962, 77725,
       87878])

### 随机抽样

In [74]:
index

array([66802, 96945, 28507, 13556,  5806, 19820, 62583, 96696, 70336,
       60913,  3024,  7119, 23414,  7976, 60371, 88647, 51866, 14849,
       81793, 53701, 60607, 78552, 34810, 70528, 31556, 96027, 75783,
        9820, 89022, 25889, 84182, 81804, 97820, 62606, 16272, 25817,
       21242, 61340, 14076, 20491, 52536,  2651, 48675, 47714, 61650,
       52523, 40382, 82613, 13123, 95719, 37252, 54415, 60169, 24811,
       15855,  6257, 31503, 58169, 55321,  6472, 86219, 82688, 28816,
       30876, 42786, 92514,  6424, 56958, 85926, 58909, 65273, 38818,
       51743, 53613, 83058, 81482, 94367, 31908, 24636, 59683, 80515,
       27747, 55020, 67145, 18407, 91576, 32258, 96966,  2126,  1664,
       12666, 86783, 61863, 25610, 15814, 94604, 75879, 88112, 90683,
       75027, 37299, 61277, 36227, 59438, 34923, 66095, 19353, 97574,
        3311, 73352, 60429, 83390, 86019, 81560, 77735,  7927, 60904,
       43808, 19015, 56158, 29704, 78558, 40253, 17968, 17227, 62874,
       81909, 64106, 97926, 67339, 95347, 42382, 82673, 13510, 56693,
       44263, 78946, 51387, 20323, 28253,  5899,  1490, 74692, 11802,
       57232, 61851,  4854, 92083, 50204, 37102,  1685, 32071, 13557,
       82556, 34071, 88887, 95871,  9625, 30254, 85946, 29519, 21465,
       17912, 70118, 13519, 62886, 21158, 89839, 53560, 29810, 82275,
       15952, 96927, 97169, 60085, 79374, 69540, 32691, 11953, 89176,
       84727, 59802, 31056, 69321, 51012, 22184, 25223, 55957, 96790,
       19551, 10264, 64689, 53994, 52910,  6026, 32636, 28315, 97911,
       84888, 62861, 77242, 19607, 17905, 70457, 51085, 55505, 87778,
       63423, 46920, 85718, 63978,  6577, 73849, 51748, 92641, 71453,
       57427, 16062, 30264, 11464, 14027, 43691, 21965, 83094, 46523,
       30695, 38613,  2951, 66142, 31196, 34218, 35373,  9142, 85290,
       88408,  1681, 80232,  2289, 83794, 35192, 16952, 19061, 26296,
       30082, 60708, 94101, 90708, 69367, 95281, 40064, 85598, 77421,
       37895, 44629,  3476, 86136, 86665, 90025, 22590, 35195, 97783,
       40162, 39901, 20462, 18349, 20016, 67965,  9237, 28527, 57754,
       34563, 99682, 28554,  1243, 64822, 97203,  5674, 52793, 58627,
       84995, 94013, 11123,  4856, 80473, 37615, 13085, 55019, 29904,
       31936, 53183,  7402, 50187, 97948, 54694, 36301, 63319, 38575,
        2338, 29581, 82447, 32423, 47413, 50742, 59379, 10195, 68441,
       95512, 61886, 74104, 57459, 99685, 16670, 35687, 83951, 11299,
       52631, 57904, 51033, 55560, 23116, 97116, 25823, 94654, 72845,
       80487, 29388, 85221, 60312,  3594, 50185, 57553, 64618, 23546,
       35926,  2365, 65242,  7003, 58830, 84161,  4839, 24243, 34090,
       35183, 48586,  2114, 66993, 88204, 99690, 32823, 92709, 41410,
       57716, 41801, 28328, 14971, 26961, 92371,  1789,  8721,  7451,
       76530, 21050, 65123, 44730, 67816, 34507, 23402, 60984, 45200,
       56094, 17826, 52533,  1534, 31462, 23358, 18164, 90214, 16930,
       51590, 67051, 64739, 46052,  1095, 17384, 24933, 77962, 89696,
       40925,  1756, 42672, 93293, 27733, 76151, 89087, 71545, 35002,
       62951, 20902, 94346, 63253, 86540, 14559, 27559, 80507, 52788,
       26575, 33677,  3761, 87436,  7451, 53122, 80116, 32206, 14590,
       81336, 32843, 67442, 39124, 83365, 87146, 80138, 96834, 45122,
       29786, 94242, 50846, 38321,  9409, 16684, 40494, 98000,  6810,
       22615, 34309,  4891, 83009, 57804, 22276, 27788, 14187, 97828,
       56068, 82852, 23439, 49681, 60412, 88147, 74207, 41857, 23769,
       91078, 53664,  5249, 36676, 90651, 80426, 93893, 55003, 51820,
       43982, 18051, 18614, 56162, 31117, 22860, 47024, 81242, 48230,
       14702, 14185, 85460, 60648, 75788, 61988, 45599, 60970, 22124,
       60871, 55710,  2888,  9892, 60779, 59421, 10543, 35165, 20443,
       20843,  9196, 14888, 24740, 91393, 68949, 61468, 46426, 33396,
       77541, 85839, 18924, 62115, 15345, 78459, 65717, 57350, 22239,
       46994, 37143, 50029, 76750, 10861, 48207, 14338, 50428, 83034,
        7095, 81375, 22697, 10989, 96049, 13948, 95218, 87956, 77443,
       26056, 57082, 46000, 85440, 24283, 93117, 26614, 20126, 55603,
       19066, 20053, 26875, 65403, 38826, 61257, 56943,   501, 80510,
       73690, 25376, 73725, 30908, 72210,  6151, 82642, 29112, 99811,
       71666,  6962, 41380, 97627, 12385,  8807, 11010,  6047, 39430,
       55800, 30733, 37886, 51589, 70477, 79429, 39691, 12519, 10470,
       25663, 10702, 42025, 19294, 15236, 33748, 60851, 60563, 23260,
       11491,  4717, 25725, 83677, 27257, 14571, 83915, 58674, 49849,
       42235, 59361, 48041, 99328, 39653, 86517, 48384, 13926, 51160,
       58086, 23211, 28160, 37602, 19660, 21344, 78050, 30673, 14986,
       23746, 47614, 51287, 50089, 90161, 66339, 43909, 45694, 16435,
       20092, 67625, 53896, 36185, 84269, 32305, 47036, 38783, 64540,
       36715, 51245, 84969, 91143, 81395, 58375, 25544, 92109, 20060,
       98466, 45716, 24947, 17804, 67627, 29517, 16988,  7954, 94506,
       53641, 24128, 56452, 33584, 57759, 49902, 73194, 55237, 59432,
       36454,  5349,  8631, 37757, 30594, 40196, 69931, 58769, 44291,
       86759, 40563, 43609, 66636, 16993,  5685, 33822, 85932, 15252,
       68279,  3260, 78420, 67318, 29632, 11903, 28058, 80148, 42337,
       62295, 74103, 40055, 54202,   280, 31738, 60228, 80894, 30582,
       25861,  6773,  1467, 17992, 31062, 82150, 69231, 59438, 32282,
       27353, 30939, 75641, 34007,  6112, 50792, 25333, 73229, 97749,
        2942, 27741, 68266, 53233, 12958, 96661, 11185, 87257, 13850,
        9930, 24947, 36203, 48207, 23082, 56241, 71572, 33621, 60084,
       89682, 74917, 91372, 14071, 82132, 73170, 65703,  6056, 11743,
       43620, 52608, 16767, 76130, 22574,  5399, 56512,  9966, 97528,
       55914, 92770, 97345, 63263, 96860, 35158, 31841, 27978, 50158,
       30561, 74289, 53090, 26710, 26029, 49161, 83290, 12599, 29367,
       75207,  5317, 63295, 57196, 18622, 98009, 90695, 65451, 21944,
       73257, 49812, 79721, 84468, 53957, 32391, 83932, 26771, 78938,
       21107, 79540, 52255, 14408, 57956, 90498, 82398, 72726, 17659,
        3235, 18456, 52439, 72833, 72317, 53222, 74563, 40108, 69243,
       47143, 47400, 25489, 86510,  9566, 67821, 82696, 94153, 64330,
       18577, 35313, 55405, 66877, 20829, 34674, 25030, 44995, 72102,
       12596, 80312, 43108, 83291, 38160,  5223, 44165, 64901, 42198,
       21710,   136, 13306, 47730, 79863, 38058, 34206, 28418, 23484,
       98105, 70534, 54898, 25978, 81365, 61206, 14038, 50066, 99866,
        5402, 13186, 49016, 34969, 57553, 31329, 71314, 10703, 11370,
       80958, 18310, 51352, 60414, 48170, 20624, 58278, 84831,  3385,
       64294, 17226, 45981, 23667, 59674,  4587, 50347, 98747,  6998,
       12371, 67087, 20601, 11729, 33277, 81477, 10666, 15085, 58219,
       26771, 34122, 71368, 51874, 94548, 61369, 88559, 38673, 21997,
        3185,  8446,  8663, 70529,  8215, 36870, 59551, 72235, 48312,
       39351, 53588, 22301, 62017, 62145, 28456, 31150, 86167, 45780,
       81481, 44319, 36393, 86016, 86843, 95396, 37113, 87290, 12840,
        7780, 86208, 47783, 95561, 84559,  4272, 40460, 26686,  3131,
       59008, 27987, 69349, 92921, 25093, 32245, 40024, 21953, 98082,
       67014, 20318, 64141, 88895, 14920, 81580, 62409, 30046, 39456,
       89789, 43321, 24935, 11670, 26374, 70229, 38719, 74794, 99891,
       67776, 37325, 26289, 90041, 35309, 77408,  2402, 47175, 24542,
       13388, 84764, 85105, 23137, 41583, 44330,  8467, 61702, 74938,
       62144, 11996,  8057, 86300, 79483, 74463, 10731, 99394, 92035,
       58295, 98790, 66090, 90449, 14795, 50261, 86578, 32186, 62396,
        8252, 27835, 52407, 31259, 26396, 26680, 62214, 53583,   406,
       99179, 36382, 96144, 56267, 27090, 52813, 97492, 92962, 77725,
       87878])

In [72]:
df[index]

KeyError: '[66802 96945 28507 13556  5806 19820 62583 96696 70336 60913  3024  7119\n 23414  7976 60371 88647 51866 14849 81793 53701 60607 78552 34810 70528\n 31556 96027 75783  9820 89022 25889 84182 81804 97820 62606 16272 25817\n 21242 61340 14076 20491 52536  2651 48675 47714 61650 52523 40382 82613\n 13123 95719 37252 54415 60169 24811 15855  6257 31503 58169 55321  6472\n 86219 82688 28816 30876 42786 92514  6424 56958 85926 58909 65273 38818\n 51743 53613 83058 81482 94367 31908 24636 59683 80515 27747 55020 67145\n 18407 91576 32258 96966  2126  1664 12666 86783 61863 25610 15814 94604\n 75879 88112 90683 75027 37299 61277 36227 59438 34923 66095 19353 97574\n  3311 73352 60429 83390 86019 81560 77735  7927 60904 43808 19015 56158\n 29704 78558 40253 17968 17227 62874 81909 64106 97926 67339 95347 42382\n 82673 13510 56693 44263 78946 51387 20323 28253  5899  1490 74692 11802\n 57232 61851  4854 92083 50204 37102  1685 32071 13557 82556 34071 88887\n 95871  9625 30254 85946 29519 21465 17912 70118 13519 62886 21158 89839\n 53560 29810 82275 15952 96927 97169 60085 79374 69540 32691 11953 89176\n 84727 59802 31056 69321 51012 22184 25223 55957 96790 19551 10264 64689\n 53994 52910  6026 32636 28315 97911 84888 62861 77242 19607 17905 70457\n 51085 55505 87778 63423 46920 85718 63978  6577 73849 51748 92641 71453\n 57427 16062 30264 11464 14027 43691 21965 83094 46523 30695 38613  2951\n 66142 31196 34218 35373  9142 85290 88408  1681 80232  2289 83794 35192\n 16952 19061 26296 30082 60708 94101 90708 69367 95281 40064 85598 77421\n 37895 44629  3476 86136 86665 90025 22590 35195 97783 40162 39901 20462\n 18349 20016 67965  9237 28527 57754 34563 99682 28554  1243 64822 97203\n  5674 52793 58627 84995 94013 11123  4856 80473 37615 13085 55019 29904\n 31936 53183  7402 50187 97948 54694 36301 63319 38575  2338 29581 82447\n 32423 47413 50742 59379 10195 68441 95512 61886 74104 57459 99685 16670\n 35687 83951 11299 52631 57904 51033 55560 23116 97116 25823 94654 72845\n 80487 29388 85221 60312  3594 50185 57553 64618 23546 35926  2365 65242\n  7003 58830 84161  4839 24243 34090 35183 48586  2114 66993 88204 99690\n 32823 92709 41410 57716 41801 28328 14971 26961 92371  1789  8721  7451\n 76530 21050 65123 44730 67816 34507 23402 60984 45200 56094 17826 52533\n  1534 31462 23358 18164 90214 16930 51590 67051 64739 46052  1095 17384\n 24933 77962 89696 40925  1756 42672 93293 27733 76151 89087 71545 35002\n 62951 20902 94346 63253 86540 14559 27559 80507 52788 26575 33677  3761\n 87436  7451 53122 80116 32206 14590 81336 32843 67442 39124 83365 87146\n 80138 96834 45122 29786 94242 50846 38321  9409 16684 40494 98000  6810\n 22615 34309  4891 83009 57804 22276 27788 14187 97828 56068 82852 23439\n 49681 60412 88147 74207 41857 23769 91078 53664  5249 36676 90651 80426\n 93893 55003 51820 43982 18051 18614 56162 31117 22860 47024 81242 48230\n 14702 14185 85460 60648 75788 61988 45599 60970 22124 60871 55710  2888\n  9892 60779 59421 10543 35165 20443 20843  9196 14888 24740 91393 68949\n 61468 46426 33396 77541 85839 18924 62115 15345 78459 65717 57350 22239\n 46994 37143 50029 76750 10861 48207 14338 50428 83034  7095 81375 22697\n 10989 96049 13948 95218 87956 77443 26056 57082 46000 85440 24283 93117\n 26614 20126 55603 19066 20053 26875 65403 38826 61257 56943   501 80510\n 73690 25376 73725 30908 72210  6151 82642 29112 99811 71666  6962 41380\n 97627 12385  8807 11010  6047 39430 55800 30733 37886 51589 70477 79429\n 39691 12519 10470 25663 10702 42025 19294 15236 33748 60851 60563 23260\n 11491  4717 25725 83677 27257 14571 83915 58674 49849 42235 59361 48041\n 99328 39653 86517 48384 13926 51160 58086 23211 28160 37602 19660 21344\n 78050 30673 14986 23746 47614 51287 50089 90161 66339 43909 45694 16435\n 20092 67625 53896 36185 84269 32305 47036 38783 64540 36715 51245 84969\n 91143 81395 58375 25544 92109 20060 98466 45716 24947 17804 67627 29517\n 16988  7954 94506 53641 24128 56452 33584 57759 49902 73194 55237 59432\n 36454  5349  8631 37757 30594 40196 69931 58769 44291 86759 40563 43609\n 66636 16993  5685 33822 85932 15252 68279  3260 78420 67318 29632 11903\n 28058 80148 42337 62295 74103 40055 54202   280 31738 60228 80894 30582\n 25861  6773  1467 17992 31062 82150 69231 59438 32282 27353 30939 75641\n 34007  6112 50792 25333 73229 97749  2942 27741 68266 53233 12958 96661\n 11185 87257 13850  9930 24947 36203 48207 23082 56241 71572 33621 60084\n 89682 74917 91372 14071 82132 73170 65703  6056 11743 43620 52608 16767\n 76130 22574  5399 56512  9966 97528 55914 92770 97345 63263 96860 35158\n 31841 27978 50158 30561 74289 53090 26710 26029 49161 83290 12599 29367\n 75207  5317 63295 57196 18622 98009 90695 65451 21944 73257 49812 79721\n 84468 53957 32391 83932 26771 78938 21107 79540 52255 14408 57956 90498\n 82398 72726 17659  3235 18456 52439 72833 72317 53222 74563 40108 69243\n 47143 47400 25489 86510  9566 67821 82696 94153 64330 18577 35313 55405\n 66877 20829 34674 25030 44995 72102 12596 80312 43108 83291 38160  5223\n 44165 64901 42198 21710   136 13306 47730 79863 38058 34206 28418 23484\n 98105 70534 54898 25978 81365 61206 14038 50066 99866  5402 13186 49016\n 34969 57553 31329 71314 10703 11370 80958 18310 51352 60414 48170 20624\n 58278 84831  3385 64294 17226 45981 23667 59674  4587 50347 98747  6998\n 12371 67087 20601 11729 33277 81477 10666 15085 58219 26771 34122 71368\n 51874 94548 61369 88559 38673 21997  3185  8446  8663 70529  8215 36870\n 59551 72235 48312 39351 53588 22301 62017 62145 28456 31150 86167 45780\n 81481 44319 36393 86016 86843 95396 37113 87290 12840  7780 86208 47783\n 95561 84559  4272 40460 26686  3131 59008 27987 69349 92921 25093 32245\n 40024 21953 98082 67014 20318 64141 88895 14920 81580 62409 30046 39456\n 89789 43321 24935 11670 26374 70229 38719 74794 99891 67776 37325 26289\n 90041 35309 77408  2402 47175 24542 13388 84764 85105 23137 41583 44330\n  8467 61702 74938 62144 11996  8057 86300 79483 74463 10731 99394 92035\n 58295 98790 66090 90449 14795 50261 86578 32186 62396  8252 27835 52407\n 31259 26396 26680 62214 53583   406 99179 36382 96144 56267 27090 52813\n 97492 92962 77725 87878] not in index'

当DataFrame规模足够大时，直接使用np.random.randint()函数，就配合take()函数实现随机抽样

In [73]:
# take 取拿
df.take(index)

            red     green      blue
66802 -1.023118 -0.085559  0.519395
96945  1.355709 -0.582051  0.604630
28507 -0.294973  0.487209  0.373317
13556  1.397707 -0.508674 -1.279619
5806  -0.097024  0.629599  1.083998
19820  1.534288  1.197120  0.459728
62583 -0.203075  0.930804  0.198746
96696  1.230543 -0.977554 -0.162854
70336  1.012338  2.338702 -0.232136
60913 -2.029101  0.309442  0.664203
3024   1.989839 -0.873654  0.764240
7119  -0.179773 -1.488926 -0.178023
23414 -0.918404 -0.252456 -0.489317
7976   0.396385 -0.690274 -0.961751
60371 -1.843168  0.645615  0.812366
88647  0.043953 -1.484500  1.748865
51866 -1.087555  0.740670  0.122204
14849 -0.574310  0.045808 -0.018838
81793 -0.634796 -1.214274 -0.695374
53701  0.123028 -1.556006 -0.616267
60607  1.134252 -0.847342 -0.038696
78552 -0.672605 -1.138834 -1.708758
34810  0.926342 -1.041117  0.409746
70528  1.117338  0.046141 -0.088690
31556 -2.302266 -0.687719  0.319716
96027  2.361066  0.907683  0.577671
75783 -1.893509  2.684317 -1.478256
9820   0.018054  1.424901  0.052976
89022  0.039378  1.021095  0.144531
25889 -0.312553  1.146592 -0.431604
...         ...       ...       ...
99394 -0.894685 -0.300925 -0.605022
92035 -0.899804 -2.111201  0.955363
58295 -0.532470 -0.189093 -0.167513
98790 -0.831765  0.426242  0.240315
66090 -2.137290 -3.186081  1.225814
90449  1.266282 -0.694701 -0.429483
14795  1.254187 -2.263164  1.135615
50261 -0.455812 -0.217026  0.159440
86578 -0.612479 -0.501817 -0.072751
32186 -1.702699  0.050772 -0.837459
62396 -0.083780  1.711542  0.673053
8252  -0.184931 -1.259934 -1.274046
27835  0.209919  0.784432  1.415782
52407 -0.091637  0.181313  1.632698
31259 -1.224919  0.391486  0.399350
26396  0.835244  0.850546  2.284742
26680  0.596804 -0.285661 -0.448655
62214  0.317110  0.151636 -0.457063
53583 -0.329881 -1.093309 -0.261076
406    0.471233  0.495407  1.621452
99179 -0.341540 -0.992076 -0.327719
36382  0.243983 -0.428225  1.263960
96144  0.043022  0.276743  1.200364
56267  0.747852  0.583912 -0.074948
27090 -1.068440  0.625664  0.244075
52813 -1.112879  0.888862 -0.405538
97492  1.343092 -1.117808 -0.302916
92962 -1.122574 -0.783707  0.297346
77725  1.601125  1.448037  1.127865
87878  1.448786 -0.150032  1.089896

[1000 rows x 3 columns]

============================================
练习22：

   假设有张三李四王老五的期中考试成绩ddd2，对着三名同学随机排序

============================================

## 5. 数据聚合【重点】

数据聚合是数据处理的最后一步，通常是要使每一个数组生成一个单一的数值。

数据分类处理：

 - 分组：先把数据分为几组
 - 用函数处理：为不同组的数据应用不同的函数以转换数据
 - 合并：把不同组得到的结果合并起来
 
数据分类处理的核心：
     groupby()函数

In [75]:
df = DataFrame({'item':np.random.randint(0,10,size = 100),
                'sailer':np.random.randint(0,10,size = 100),
                'weight':np.random.randint(30,300,size = 100),
                'price':np.random.randint(1,20,size = 100)})
df

    item  sailer  weight  price
0      5       2      38      4
1      0       4     154      7
2      7       6     296     10
3      9       9     116     16
4      7       8     238      2
5      3       1     150     12
6      0       2      57     16
7      5       6     230      7
8      6       7      89      6
9      5       2     273     13
10     2       7      91      7
11     5       6     267     14
12     0       3      35     17
13     0       1     164     13
14     2       7     236      3
15     1       7     260     19
16     6       0     134     17
17     1       4     119     19
18     0       5     245      2
19     9       0     196     17
20     5       2     255      6
21     3       7      57      3
22     0       1     177      9
23     0       6     276     12
24     2       8     202      6
25     2       7     102     18
26     0       4     124      6
27     0       2      35     13
28     6       3     177      8
29     2       2      82     18
..   ...     ...     ...    ...
70     1       7     172     11
71     1       0     244     19
72     9       2     285      1
73     3       3     232     11
74     2       3      72     14
75     1       8     244      4
76     7       0     113      7
77     7       4     272      4
78     2       9     257     11
79     7       5     279      3
80     7       4     240      9
81     4       0     268      5
82     5       6      74     15
83     7       0     274     11
84     6       9     235     11
85     4       2     197      1
86     8       8     288      8
87     8       9      54      9
88     3       9     110     19
89     3       3      67      6
90     5       0      78     11
91     7       3      46     12
92     6       9     121      3
93     7       5     157     11
94     8       8     234     18
95     8       3     177     14
96     5       2     118     11
97     0       8     217     16
98     7       3      79     19
99     1       6      93     15

[100 rows x 4 columns]

In [76]:
def convert_item(x):
    if x < 2:
        return '萝卜'
    elif x <7:
        return '白菜'
    else:
        return '青椒'

df['item'] = df['item'].map(convert_item)

In [77]:
df

   item  sailer  weight  price
0    白菜       2      38      4
1    萝卜       4     154      7
2    青椒       6     296     10
3    青椒       9     116     16
4    青椒       8     238      2
5    白菜       1     150     12
6    萝卜       2      57     16
7    白菜       6     230      7
8    白菜       7      89      6
9    白菜       2     273     13
10   白菜       7      91      7
11   白菜       6     267     14
12   萝卜       3      35     17
13   萝卜       1     164     13
14   白菜       7     236      3
15   萝卜       7     260     19
16   白菜       0     134     17
17   萝卜       4     119     19
18   萝卜       5     245      2
19   青椒       0     196     17
20   白菜       2     255      6
21   白菜       7      57      3
22   萝卜       1     177      9
23   萝卜       6     276     12
24   白菜       8     202      6
25   白菜       7     102     18
26   萝卜       4     124      6
27   萝卜       2      35     13
28   白菜       3     177      8
29   白菜       2      82     18
..  ...     ...     ...    ...
70   萝卜       7     172     11
71   萝卜       0     244     19
72   青椒       2     285      1
73   白菜       3     232     11
74   白菜       3      72     14
75   萝卜       8     244      4
76   青椒       0     113      7
77   青椒       4     272      4
78   白菜       9     257     11
79   青椒       5     279      3
80   青椒       4     240      9
81   白菜       0     268      5
82   白菜       6      74     15
83   青椒       0     274     11
84   白菜       9     235     11
85   白菜       2     197      1
86   青椒       8     288      8
87   青椒       9      54      9
88   白菜       9     110     19
89   白菜       3      67      6
90   白菜       0      78     11
91   青椒       3      46     12
92   白菜       9     121      3
93   青椒       5     157     11
94   青椒       8     234     18
95   青椒       3     177     14
96   白菜       2     118     11
97   萝卜       8     217     16
98   青椒       3      79     19
99   萝卜       6      93     15

[100 rows x 4 columns]

In [78]:
def convert_sailer(x):
    if x <5:
        return '张大妈'
    elif x <7:
        return '李大妈'
    else:
        return '赵大爷'

df['sailer'] = df['sailer'].map(convert_sailer)

In [79]:
df

   item sailer  weight  price
0    白菜    张大妈      38      4
1    萝卜    张大妈     154      7
2    青椒    李大妈     296     10
3    青椒    赵大爷     116     16
4    青椒    赵大爷     238      2
5    白菜    张大妈     150     12
6    萝卜    张大妈      57     16
7    白菜    李大妈     230      7
8    白菜    赵大爷      89      6
9    白菜    张大妈     273     13
10   白菜    赵大爷      91      7
11   白菜    李大妈     267     14
12   萝卜    张大妈      35     17
13   萝卜    张大妈     164     13
14   白菜    赵大爷     236      3
15   萝卜    赵大爷     260     19
16   白菜    张大妈     134     17
17   萝卜    张大妈     119     19
18   萝卜    李大妈     245      2
19   青椒    张大妈     196     17
20   白菜    张大妈     255      6
21   白菜    赵大爷      57      3
22   萝卜    张大妈     177      9
23   萝卜    李大妈     276     12
24   白菜    赵大爷     202      6
25   白菜    赵大爷     102     18
26   萝卜    张大妈     124      6
27   萝卜    张大妈      35     13
28   白菜    张大妈     177      8
29   白菜    张大妈      82     18
..  ...    ...     ...    ...
70   萝卜    赵大爷     172     11
71   萝卜    张大妈     244     19
72   青椒    张大妈     285      1
73   白菜    张大妈     232     11
74   白菜    张大妈      72     14
75   萝卜    赵大爷     244      4
76   青椒    张大妈     113      7
77   青椒    张大妈     272      4
78   白菜    赵大爷     257     11
79   青椒    李大妈     279      3
80   青椒    张大妈     240      9
81   白菜    张大妈     268      5
82   白菜    李大妈      74     15
83   青椒    张大妈     274     11
84   白菜    赵大爷     235     11
85   白菜    张大妈     197      1
86   青椒    赵大爷     288      8
87   青椒    赵大爷      54      9
88   白菜    赵大爷     110     19
89   白菜    张大妈      67      6
90   白菜    张大妈      78     11
91   青椒    张大妈      46     12
92   白菜    赵大爷     121      3
93   青椒    李大妈     157     11
94   青椒    赵大爷     234     18
95   青椒    张大妈     177     14
96   白菜    张大妈     118     11
97   萝卜    赵大爷     217     16
98   青椒    张大妈      79     19
99   萝卜    李大妈      93     15

[100 rows x 4 columns]

In [81]:
def convert_weight(x):
    if x < 80:
        return 50
    elif x <150:
        return 100
    else:
        return 150

df['weight'] = df['weight'].transform(convert_weight)

In [82]:
df

   item sailer  weight  price
0    白菜    张大妈      50      4
1    萝卜    张大妈     150      7
2    青椒    李大妈     150     10
3    青椒    赵大爷     100     16
4    青椒    赵大爷     150      2
5    白菜    张大妈     150     12
6    萝卜    张大妈      50     16
7    白菜    李大妈     150      7
8    白菜    赵大爷     100      6
9    白菜    张大妈     150     13
10   白菜    赵大爷     100      7
11   白菜    李大妈     150     14
12   萝卜    张大妈      50     17
13   萝卜    张大妈     150     13
14   白菜    赵大爷     150      3
15   萝卜    赵大爷     150     19
16   白菜    张大妈     100     17
17   萝卜    张大妈     100     19
18   萝卜    李大妈     150      2
19   青椒    张大妈     150     17
20   白菜    张大妈     150      6
21   白菜    赵大爷      50      3
22   萝卜    张大妈     150      9
23   萝卜    李大妈     150     12
24   白菜    赵大爷     150      6
25   白菜    赵大爷     100     18
26   萝卜    张大妈     100      6
27   萝卜    张大妈      50     13
28   白菜    张大妈     150      8
29   白菜    张大妈     100     18
..  ...    ...     ...    ...
70   萝卜    赵大爷     150     11
71   萝卜    张大妈     150     19
72   青椒    张大妈     150      1
73   白菜    张大妈     150     11
74   白菜    张大妈      50     14
75   萝卜    赵大爷     150      4
76   青椒    张大妈     100      7
77   青椒    张大妈     150      4
78   白菜    赵大爷     150     11
79   青椒    李大妈     150      3
80   青椒    张大妈     150      9
81   白菜    张大妈     150      5
82   白菜    李大妈      50     15
83   青椒    张大妈     150     11
84   白菜    赵大爷     150     11
85   白菜    张大妈     150      1
86   青椒    赵大爷     150      8
87   青椒    赵大爷      50      9
88   白菜    赵大爷     100     19
89   白菜    张大妈      50      6
90   白菜    张大妈      50     11
91   青椒    张大妈      50     12
92   白菜    赵大爷     100      3
93   青椒    李大妈     150     11
94   青椒    赵大爷     150     18
95   青椒    张大妈     150     14
96   白菜    张大妈     100     11
97   萝卜    赵大爷     150     16
98   青椒    张大妈      50     19
99   萝卜    李大妈     100     15

[100 rows x 4 columns]

In [83]:
# 统计这一个月，张大妈，李大妈，赵大爷，销售了多少斤蔬菜
ret = df.groupby(['sailer'])['weight']
ret

In [84]:
# 分好组了，没有进行计算,销售总额，就是求和
ret.sum()

sailer
张大妈    6450
李大妈    2100
赵大爷    3700
Name: weight, dtype: int64

In [86]:
ret.max()

sailer
张大妈    150
李大妈    150
赵大爷    150
Name: weight, dtype: int64

In [87]:
ret.apply(np.sum)

sailer
张大妈    6450
李大妈    2100
赵大爷    3700
Name: weight, dtype: int64

In [88]:
# 算次数
ret.count()

sailer
张大妈    56
李大妈    15
赵大爷    29
Name: weight, dtype: int64

In [92]:
ret.apply(np.size)

sailer
张大妈    56
李大妈    15
赵大爷    29
Name: weight, dtype: int64

In [94]:
def count(x):
    return x.size

In [93]:
ret.apply(count)

NameError: name 'count' is not defined

In [95]:
ret.apply(count)

sailer
张大妈    56
李大妈    15
赵大爷    29
Name: weight, dtype: int64

In [99]:
3.14.round(1)

AttributeError: 'float' object has no attribute 'round'

In [102]:
def analysis(x):
    return (x.size,x.sum(),np.round(x.mean(),decimals=2),x.min())

ret.apply(analysis)

sailer
张大妈    (56, 6450, 115.18, 50)
李大妈     (15, 2100, 140.0, 50)
赵大爷    (29, 3700, 127.59, 50)
Name: weight, dtype: object

In [103]:
df

   item sailer  weight  price
0    白菜    张大妈      50      4
1    萝卜    张大妈     150      7
2    青椒    李大妈     150     10
3    青椒    赵大爷     100     16
4    青椒    赵大爷     150      2
5    白菜    张大妈     150     12
6    萝卜    张大妈      50     16
7    白菜    李大妈     150      7
8    白菜    赵大爷     100      6
9    白菜    张大妈     150     13
10   白菜    赵大爷     100      7
11   白菜    李大妈     150     14
12   萝卜    张大妈      50     17
13   萝卜    张大妈     150     13
14   白菜    赵大爷     150      3
15   萝卜    赵大爷     150     19
16   白菜    张大妈     100     17
17   萝卜    张大妈     100     19
18   萝卜    李大妈     150      2
19   青椒    张大妈     150     17
20   白菜    张大妈     150      6
21   白菜    赵大爷      50      3
22   萝卜    张大妈     150      9
23   萝卜    李大妈     150     12
24   白菜    赵大爷     150      6
25   白菜    赵大爷     100     18
26   萝卜    张大妈     100      6
27   萝卜    张大妈      50     13
28   白菜    张大妈     150      8
29   白菜    张大妈     100     18
..  ...    ...     ...    ...
70   萝卜    赵大爷     150     11
71   萝卜    张大妈     150     19
72   青椒    张大妈     150      1
73   白菜    张大妈     150     11
74   白菜    张大妈      50     14
75   萝卜    赵大爷     150      4
76   青椒    张大妈     100      7
77   青椒    张大妈     150      4
78   白菜    赵大爷     150     11
79   青椒    李大妈     150      3
80   青椒    张大妈     150      9
81   白菜    张大妈     150      5
82   白菜    李大妈      50     15
83   青椒    张大妈     150     11
84   白菜    赵大爷     150     11
85   白菜    张大妈     150      1
86   青椒    赵大爷     150      8
87   青椒    赵大爷      50      9
88   白菜    赵大爷     100     19
89   白菜    张大妈      50      6
90   白菜    张大妈      50     11
91   青椒    张大妈      50     12
92   白菜    赵大爷     100      3
93   青椒    李大妈     150     11
94   青椒    赵大爷     150     18
95   青椒    张大妈     150     14
96   白菜    张大妈     100     11
97   萝卜    赵大爷     150     16
98   青椒    张大妈      50     19
99   萝卜    李大妈     100     15

[100 rows x 4 columns]

In [104]:
g = df.groupby(['sailer','item'])
g

In [105]:
g.mean()

                 weight      price
sailer item
张大妈    白菜    108.695652   9.869565
       萝卜    106.250000  12.937500
       青椒    132.352941   9.117647
李大妈    白菜    133.333333  10.166667
       萝卜    137.500000   9.000000
       青椒    150.000000  10.600000
赵大爷    白菜    125.000000  10.142857
       萝卜    150.000000  12.500000
       青椒    116.666667   9.000000

In [106]:
g.min()

             weight  price
sailer item
张大妈    白菜        50      1
       萝卜        50      1
       青椒        50      1
李大妈    白菜        50      3
       萝卜       100      2
       青椒       150      3
赵大爷    白菜        50      3
       萝卜       150      4
       青椒        50      1

In [107]:
g.sum()

             weight  price
sailer item
张大妈    白菜      2500    227
       萝卜      1700    207
       青椒      2250    155
李大妈    白菜       800     61
       萝卜       550     36
       青椒       750     53
赵大爷    白菜      1750    142
       萝卜       900     75
       青椒      1050     81

In [113]:
g.apply(np.std)

                price     weight
sailer item
张大妈    白菜    5.375503  43.369429
       萝卜    5.116991  42.847841
       青椒    5.454435  34.046579
李大妈    白菜    4.450343  37.267800
       萝卜    4.949747  21.650635
       青椒    5.083306   0.000000
赵大爷    白菜    5.617030  31.339159
       萝卜    4.645787   0.000000
       青椒    5.830952  40.824829

In [114]:
# 价格求平均，销量求和
g.agg(['mean','sum'])

                 weight            price
                   mean   sum       mean  sum
sailer item
张大妈    白菜    108.695652  2500   9.869565  227
       萝卜    106.250000  1700  12.937500  207
       青椒    132.352941  2250   9.117647  155
李大妈    白菜    133.333333   800  10.166667   61
       萝卜    137.500000   550   9.000000   36
       青椒    150.000000   750  10.600000   53
赵大爷    白菜    125.000000  1750  10.142857  142
       萝卜    150.000000   900  12.500000   75
       青椒    116.666667  1050   9.000000   81

In [116]:
g.agg({'weight':'sum','price':'mean'}).round(2)

             weight  price
sailer item
张大妈    白菜      2500   9.87
       萝卜      1700  12.94
       青椒      2250   9.12
李大妈    白菜       800  10.17
       萝卜       550   9.00
       青椒       750  10.60
赵大爷    白菜      1750  10.14
       萝卜       900  12.50
       青椒      1050   9.00

如果想使用color列索引，计算price1的均值，可以先获取到price1列，然后再调用groupby函数，用参数指定color这一列

使用.groups属性查看各行的分组情况：

============================================

练习23：

   假设菜市场张大妈在卖菜，有以下属性：
   
   菜品(item)：萝卜，白菜，辣椒，冬瓜
   
   颜色(color)：白，青，红
   
   重量(weight)
   
   价格(price)
   
1. 要求以属性作为列索引，新建一个ddd
2. 对ddd进行聚合操作，求出颜色为白色的价格总和
3. 对ddd进行聚合操作，求出萝卜的所有重量(包括白萝卜，胡萝卜，青萝卜）以及平均价格
4. 使用merge合并总重量及平均价格

============================================

## 6.0 高级数据聚合

可以使用pd.merge()函数将聚合操作的计算结果添加到df的每一行  
使用groupby分组后调用加和等函数进行运算，让后最后可以调用add_prefix()，来修改列名

### 可以使用transform和apply实现相同功能

在transform或者apply中传入函数即可

### transform()与apply()函数还能传入一个函数或者lambda

`
df = DataFrame({'color':['white','black','white','white','black','black'],
               'status':['up','up','down','down','down','up'],
               'value1':[12.33,14.55,22.34,27.84,23.40,18.33],
               'value2':[11.23,31.80,29.99,31.18,18.25,22.44]})
`

apply的操作对象，也就是传给lambda的参数是整列的数组

============================================

练习24：

   使用transform与apply实现练习23的功能

============================================